{% set name = "log_proxy" %}
{% set version = "0.0.9" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    #path: ../
    url: https://github.com/metwork-framework/{{ name }}/archive/v{{ version }}.tar.gz
    fn: v{{ version }}.tar.gz
    md5: 906fc1cb87a18122d2b37ca96d96d321

build:
    number: 1
    run_exports:
        - glib

requirements:
    build:
        - pkgconfig
        - {{ compiler('c') }}
    host:
        - glib >2.58

about:
    description: {{ name }} is a tiny C utility for log rotation for apps that write their logs to stdout
    home: https://github.com/metwork-framework/{{ name }}/
    license: BSD

