package:
    name: log_proxy
    version: v0.0.8

source:
    #path: ../
    url: https://github.com/metwork-framework/log_proxy/archive/v0.0.9.tar.gz
    fn: v0.0.9.tar.gz
    md5: 906fc1cb87a18122d2b37ca96d96d321

build:
    number: 1
    run_exports:
        - glib

requirements:
    build:
        - pkgconfig
        - {{ compiler('c') }}
    host:
        - glib >2.58

about:
    description: log_proxy is a tiny C utility for log rotation for apps that write their logs to stdout
    home: https://github.com/metwork-framework/log_proxy/
    license: BSD

