name: build

on:
  push:
    branches: [ master, testfabien ]
    #  pull_request:
    #branches: [ master, testfabien ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dockebuildimage
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          name: metwork/logproxy-centos6-buildimage
          context: docker
          cache: true
          tags: "latest"
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: run
        uses: docker://metwork/logproxy-centos6-buildimage
