name: C/C++ CI

on:
  push:
    branches: [ master, testfabien ]
  pull_request:
    branches: [ master, testfabien ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dockebuildimage
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: metwork/logproxy_centos6_buildimage
          context: docker
      - name: run
        uses: docker://metwork/logproxy_centos6_buildimage
