name: C/C++ CI

on:
  push:
    branches: [ master, testfabien ]
  pull_request:
    branches: [ master, testfabien ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: ls
        run: ls -alrt

