name: C/C++ CI

on:
  push:
    branches: [ master, testfabien ]
  pull_request:
    branches: [ master, testfabien ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dockebuildimage
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: metwork/logproxy-centos6-buildimage
          context: docker
          cache: true
      - name: run
        uses: docker://metwork/logproxy_centos6_buildimage
