name: build

on:
  push:
    branches: [ master, testfabien ]
    #  pull_request:
    #branches: [ master, testfabien ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dockebuildimage
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          name: metwork/logproxy-centos6-buildimage
          context: docker
          cache: true
          tags: "latest"
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: run
        uses: docker://metwork/logproxy-centos6-buildimage
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: tar
        run: |
          mv release log_proxy-linux64-${{ steps.vars.outputs.tag }}
          tar -cvf log_proxy-linux64-${{ steps.vars.outputs.tag }}.tar log_proxy-linux64-${{ steps.vars.outputs.tag }}
          gzip log_proxy-linux64-${{ steps.vars.outputs.tag }}.tar
      - uses: actions/upload-artifact@v1
        with:
          name: log_proxy-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          path: ./log_proxy-linux64-${{ steps.vars.outputs.tag }}.tar.gz
      - name: create_release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./log_proxy-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          asset_name: log_proxy-linux64-${{ steps.vars.outputs.tag }}.tar.gz
          asset_content_type: application/gzip
