name: C/C++ CI

on:
  push:
    branches: [ master, testfabien ]
  pull_request:
    branches: [ master, testfabien ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    container: centos:6
    steps:
    - name: make
      run: make
